---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: us-law-severity-map
  namespace: us-law-severity-map
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  labels:
    app: us-law-severity-map
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - us-law-severity-map.local
      secretName: us-law-severity-map-tls
  rules:
    - host: us-law-severity-map.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: us-law-severity-map-web
                port:
                  number: 3000
